api_server/config/routes.rb
Rails.application.routes.draw do
  resources :about, only: :index
  root 'home#index'
end

api_server/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

api_server/app/models/search.rb
class Search < ApplicationRecord
end

api_server/app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @blur = 'blur'
  end
end

api_server/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_sky
  before_action :set_blur
  before_action :set_title
  before_action :get_current_user
  before_action :set_astro
  before_action :set_header_title

  # もしログインしていなければトップページにリダイレクト
  def user_sign_in_status
    redirect_to :root, notice: 'ログインしている必要な項目があります。' unless user_signed_in?
  end

  def get_current_user
    user_id = cookies[:current_user]
    logger.debug "・ω・#{user_id}"
    begin
      @current_user = User.find(user_id)
    rescue StandardError => e
      puts e
      logger.debug '[1199]::おかしなクッキーを使っているユーザーが居る'
    end
  end

  # ログイン中かどうかを確認する
  def user_signed_in?
    @current_user.nil? ? false : true
  end

  def set_blur
    @blur = ''
    @blur_on_windmill = 'blur'
  end

  def set_title
    @title = 'Marble Phantasm 優しい世界'
  end

  def set_header_title
    @title = 'Marble Phantasm'
  end

  def set_sky
    @sky = 'night_sky'
    h = Time.now.hour + 9
    logger.debug h
    case h
    when 6..16
      @sky = 'morning_sky'
    when 17..19
      @sky = 'sunset_sky'
    when 20..5
      logger.debug 'Hello?'
      @sky = 'night_sky'
    end
  end

  def set_astro
    h = Time.now.hour + 9
    @astro = if h > 0 && h < 19
               'sun'
             else
               'moon'
             end
  end
end

api_server/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[show edit update destroy]
  before_action :user_sign_in_status, only: %i[edit update destroy create new]

  # GET /blogs
  # GET /blogs.json
  def index
    page = params[:page].nil? ? 0 : params[:page]
    @blogs = Blog.order('created_at desc').page(page)
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show; end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit; end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_blog
    @blog = Blog.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def blog_params
    params.require(:blog).permit(:title, :body, :image, :user_id, :tags)
  end
end

api_server/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @blur_on_windmill = 'blur'
  end
end

api_server/app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: %i[show edit update destroy]

  def result
    logger.debug('・ω・')
    q = params[:q]
    render json: q.to_json
  end

  # GET /searches
  # GET /searches.json
  def index
    @searches = Search.all
    @search = Search.new
  end

  # GET /searches/1
  # GET /searches/1.json
  def show; end

  # GET /searches/new
  def new
    @search = Search.new
  end

  # GET /searches/1/edit
  def edit; end

  # POST /searches
  # POST /searches.json
  def create
    @search = Search.new(search_params)

    respond_to do |format|
      if @search.save
        format.html { redirect_to @search, notice: 'Search was successfully created.' }
        format.json { render :show, status: :created, location: @search }
      else
        format.html { render :new }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /searches/1
  # PATCH/PUT /searches/1.json
  def update
    respond_to do |format|
      if @search.update(search_params)
        format.html { redirect_to @search, notice: 'Search was successfully updated.' }
        format.json { render :show, status: :ok, location: @search }
      else
        format.html { render :edit }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    @search.destroy
    respond_to do |format|
      format.html { redirect_to searches_url, notice: 'Search was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_search
    @search = Search.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def search_params
    params.require(:search).permit(:q, :ip_addr)
  end
end

api_server/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # 管理画面のことである
  def show; end

  def sign_in
    @blur = 'blur'
  end

  def sign_in_process
    data = params[:user]
    if @user = login(data[:email], data[:password])
      cookies[:current_user] = @user.id
      redirect_to(:root, notice: 'ログインに成功しました')
    else
      flash.now[:alert] = 'ログインに失敗しました'
      render action: :sign_in
    end
  end

  def sign_up
    if user_signed_in?
      redirect_to :root, notice: 'すでにログインしています'
    else
      @user = User.new
    end
  end

  def create
    @user = User.new user_params
    if @user.save
      cookies[:current_user] = @user.id
      redirect_to :root, notice: '登録が完了しました'
    else
      flash[:now] = 'ユーザーの登録に失敗しました'
      render :sign_up
    end
  end

  def sign_out
    cookies.delete(:current_user)
    if cookies[:current_user].nil?
      redirect_to :root, notice: 'ログアウトしました'
    else
      redirect_to :back, notice: 'ログアウトに失敗しました'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
  end
end

api_server/app/helpers/about_helper.rb
module AboutHelper
end

api_server/app/helpers/application_helper.rb
module ApplicationHelper

	def user_signed_in?
		if @current_user.nil?
			return false
		else
			return true
		end
	end

  #RedCarpet
  def markdown(text)
    unless @markdown
      renderer = Redcarpet::Render::HTML.new
      @markdown = Redcarpet::Markdown.new(renderer)
    end
    @markdown.render(text).html_safe
  end
  
end

api_server/app/helpers/blogs_helper.rb
module BlogsHelper
end

api_server/app/helpers/home_helper.rb
module HomeHelper
end

api_server/app/helpers/searches_helper.rb
module SearchesHelper
end

api_server/app/helpers/users_helper.rb
module UsersHelper
end

api_server/app/views/about/index.html.haml
#main_container
  #main_content
    %article.container.about_card
      %h1.center-align.lato 
        ようこそ
        %br/
        %span.amber-text.thin_300 Seasons'sCall
        へ
    
    %article.container.about_card
      .card-panel
        %h1 概要
        %p
          このWEBサイトはUGによって作成＆運営されています。
          %br/
          Seasons'sCallのトップページや背景は和歌山県御坊市にある山と風車をモチーフに制作されています。
          これはUGが和歌山生まれ和歌山育ちでこの風景が県下でもっともお気に入りのスポットの１つだからです(*´∀｀*)
          %br/
          Seasons'sCallはUGのブログ＆ポートフォリオとして利用していく予定ですが、ちょくちょく難しいことや歴史なんかも書いていこうと思ってます。
          もしかしたら自作の小説なんかも作品集に加えられるかもしれません(∩´∀｀)
          
    %article.container.about_card
      .card-panel
        %h1 作者プロフィール
        %p
          20歳からプログラミングを学び始めるも難しくて挫折すること数度、３年を経てようやく理解の糸口を掴み独立。
          %br/
          一時国内で仕事をするためにはPHPの習得が必須でありRubyは邪道と言われ激怒、それ以来Ruby、Nodejsをメインに開発を続ける。
          （当人はC言語やPythonが好きでPHPはよくわかっていない。）
          
          %br/
          2015年にGo言語に出会い衝撃を受けるも未だに参考書を読んだ程度で何も作っていない。（いずれのこのサイトをGoで書き直す予定だ！）
          普段はピアノや読書、散歩を趣味としテレビは全く見ない。買ってすらいない。
          プログラミングをしているときは脳が開放されているように感じするため楽しんでいる。
          %br/
          2016年、おもむろに自転車に乗りはじめる。
          会社の健康診断でコレステロール値が上がってきてたことに恐怖を覚えたので始めたがドハマリする。
          9/1に購入し２ヶ月後にはレースに出場する。レース後に若干燃え尽き症候群を発症するもなんとか乗り切り中。
          ３ヶ月めには４０キロの世界に入門できるかもしれない。
          %br/
          愛する趣味は「プログラミング」,「ピアノ」,「自転車」
          どれか１つがうまく行ってもだめだ。
          全部上手にこなしていくんだ
          = link_to "Githubリポジトリ（役に立つ物はない）","https://github.com/suzaku183",class: "indigo-text"
    
    %article.container.about_card
      .card-panel
        %h1 名前の由来
        %p 
          Seasons'sCallという名前は和歌山出身のhide様の楽曲にあやかっています。
          %br/
          Seasons'sCallはニュースやブログ、作品集、背景の移り変わりなど四季折々の情報や風景をこのサイトでお伝えしたいという意図もありURLとして命名しました。
          %br/
          ちなみにhide様のこの曲は私の大好きなアニメ『BLOOD+』のOPにも利用されておりとても思い出深い曲です。
    
    %article.container.about_card
      .card-panel
        %h1 著作権
        %p
          このサイトにアクセスいただくと時間や季節にあわせた音楽が流れていることと思います。
          %br/
          これは運営者のUGが演奏し録音し音源として利用しています。
          %br/
          プログラマとして、ハッカー（悪いことをするハッカーではなく良い方の意味で）を目指しているUGとしては
          このサイトのソースコード、すべてGNUライセンスで公開しています。(ただし背景の山の画像だけは使用不可です！)
          流れている演奏も自由にご利用ください。ただしサーバ負荷を考慮して直リンクはご遠慮ください(*´∀｀*)
          %br/
          Seasons'sCall上で演奏されている楽曲は下記のとおりです（順不同）
          %ul
            - %W{月の光(ドビュッシー) 愛の夢(フランツ・リスト) 別れの曲(ショパン)}.each do |song|
              %li= song
:css
  .grad_background{
  /* Permalink - use to edit and share this gradient: http://colorzilla.com/gradient-editor/#b3dced+0,2aea6d+50,d2f7e9+100 */
  background: #b3dced; /* Old browsers */
  background: -moz-linear-gradient(top, #b3dced 0%, #2aea6d 50%, #d2f7e9 100%); /* FF3.6-15 */
  background: -webkit-linear-gradient(top, #b3dced 0%,#2aea6d 50%,#d2f7e9 100%); /* Chrome10-25,Safari5.1-6 */
  background: linear-gradient(to bottom, #b3dced 0%,#2aea6d 50%,#d2f7e9 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
  filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#b3dced', endColorstr='#d2f7e9',GradientType=0 ); /* IE6-9 */

  }

api_server/app/views/blogs/_form.html.haml
= form_for @blog do |f|
  - if @blog.errors.any?
    #error_explanation
      %h2= "#{pluralize(@blog.errors.count, "error")} prohibited this blog from being saved:"
      %ul
        - @blog.errors.full_messages.each do |msg|
          %li= msg
  
  .input-field
    = f.label :title,"タイトル"
    = f.text_field :title
  .input-field
    = f.label :tags, "タグ"
    = f.text_field :tags
  .input-field
    = f.label :body,"本文"
    = f.text_area :body,class: "materialize-textarea"
    
  %div(class="file-field input-field")
    .btn
      %span File
      = f.file_field :image
  %br/
  %br/
  .input-field
    = f.text_field :user_id, value: @current_user.id , type: "hidden"
    = f.submit 'Save',class: "btn btn-large blue"

api_server/app/views/blogs/edit.html.haml
.container
  %h1.thin_300.center.teal-text Editing blog

  .card-panel
    = render 'form'
    
  = link_to "記事を確認", @blog
  = link_to "戻る", blogs_path,class: "right"

api_server/app/views/blogs/index.html.haml
#main_container
  .containers#main_content
    .center
      %h4.indigo-text.thin Blog.all
    .row
      - @blogs.each do |blog|
        .col.l3.s12.m4.waves-effect.waves-light
          .card
            .card-image
              = link_to blog do
                = image_tag blog.image.thumb.url
            .card-content
              = link_to blog do
                %h6.card-title.indigo-text= truncate(blog.title,length: 8)
                
              - unless blog.tags.blank?
                - blog.tags.split(",").each do |tag|
                  .chip.cyan.white-text.waves-effect.waves-light
                    = tag
              .right-align
                %span.font_size_12.thin_300.black-text= blog.created_at.strftime("%Y-%m-%d")
              
            .card-action
              = link_to "詳しく読む",blog


- if user_signed_in?
  .fixed-action-btn
    /%a.btn-floating.btn-large.blue.darken-3()
    = link_to new_blog_path, class: "btn-floating btn-large blue darken-3" do
      %i.material-icons edit

api_server/app/views/blogs/new.html.haml
#main_container.grey.lighten-5
  .container#main_content
    .card-panel.black-text.thin_300
      .container
        %h3 新しい記事を書こう！
        
        = render 'form'
        
        = link_to 'Back', blogs_path

api_server/app/views/blogs/show.html.haml
#main_container
  .container#main_content
    .card-panel.black-text.thin_300
      .center
        = image_tag @blog.image.thumb.url, width: 120,class: "circle"
      %h4.center= @blog.title
      - unless @blog.tags.blank?
        .center
          - @blog.tags.split(",").each do |tag|
            .chip.cyan.white-text
              = tag
      %p= simple_format(markdown(@blog.body))

      = image_tag @blog.image.thumb,class: "responsive-img"

      .right-align
        %span.font_size_14= @blog.created_at.strftime("%Y-%m-%d")
      
    = link_to "一覧に戻る", blogs_path

    - if user_signed_in?
      = link_to "記事を編集する", edit_blog_path(@blog), class: "right teal-text"

api_server/app/views/home/index.html.haml
%div(class="astro #{@astro}")

api_server/app/views/layouts/_blur.html.haml
//トップページ以外にはBLURフィルターを用意する
:css
  .blur{
    filter: blur(6px);
    -webkit-filter: blur(6px);
    -ms-filter: blur(6px);
  }

api_server/app/views/layouts/_page_css.html.erb
<style>
	.blur{
		filter: blur(1px);	
		-webkit-filter: blur(1px);	
		-ms-filter: blur(1px);	
	}
  #main_container{
    width: 100%;
    height: auto;
    position: absolute;
    top: 10%;
    left: 0px;
    z-index: 180;
  }
  #main_content{
    z-index: 180;
  }
  #the_world{
    position: fixed;
    top: 0px;
    left: 0px;
  }
  #mountain{
    position: fixed;
    bottom: 0px;
    left: 0px;
    width: 100%;
    height: 70%;
    z-index: 18;
  }
  .star{
    position: fixed;
    width: 2px;
    height: 2px;
    background: white;
    border-radius: 18px;
  }
  .morning_sky{
    background: -webkit-gradient(linear, left top, left bottom, color-stop(0.88, #20d9ff), color-stop(0.01, #2959ff));
    background: -webkit-linear-gradient(top, #2959ff 1%, #20d9ff 88%);
    background: -moz-linear-gradient(top, #2959ff 1%, #20d9ff 88%);
    background: -o-linear-gradient(top, #2959ff 1%, #20d9ff 88%);
    background: -ms-linear-gradient(top, #2959ff 1%, #20d9ff 88%);
    background: linear-gradient(to bottom, #2959ff 1%, #20d9ff 88%);
  }
  .sunset_sky{
    background: -webkit-gradient(linear, left top, left bottom, color-stop(1.00, #da0b20), color-stop(0.39, #aa0813), color-stop(0.01, #2b1390));
    background: -webkit-gradient(linear, left top, left bottom, color-stop(1.00, #da420b), color-stop(0.32, #aa0813), color-stop(0.01, #2b1390));
    background: -webkit-linear-gradient(top, #2b1390 1%, #aa0813 32%, #da420b 100%);
    background: -moz-linear-gradient(top, #2b1390 1%, #aa0813 32%, #da420b 100%);
    background: -o-linear-gradient(top, #2b1390 1%, #aa0813 32%, #da420b 100%);
    background: -ms-linear-gradient(top, #2b1390 1%, #aa0813 32%, #da420b 100%);
    background: linear-gradient(to bottom, #2b1390 1%, #aa0813 32%, #da420b 100%);

  }
  .night_sky{
     background: -webkit-gradient(linear, left top, left bottom, color-stop(1.00, #083268), color-stop(0.01, #2b29b3));
     background: -webkit-linear-gradient(top, #2b29b3 1%, #083268 100%);
     background: -moz-linear-gradient(top, #2b29b3 1%, #083268 100%);
     background: -o-linear-gradient(top, #2b29b3 1%, #083268 100%);
     background: -ms-linear-gradient(top, #2b29b3 1%, #083268 100%);
     background: linear-gradient(to bottom, #2b29b3 1%, #083268 100%);
  }
	
	@media screen and (max-width: 380px){
  	.windmill{
  	  width: 33%;
  	  height: 50%;
  	  position: fixed;
  	  bottom: 15%;
  	  z-index: 6;
  	}
  	.windmill_relative{
  	  position: relative;
  	  width: 100%;
  	  height: 100%;
  	}
  	.lod{
  	  width: 66%;
  	  height: auto;
  	  position: absolute;
  	  bottom: 0px;
  	  left: 40%;
  	  z-index: 8;
  	}
  	.wind{
  	  width: 100%;
  	  height: auto;
  	  position: absolute;
  	  bottom: 2%;
  	  left: 23%;
  	  z-index: 12;
		}

		#windmill_1{
			display: block;
			left: 10%;
			bottom: 18%;
		}
		#windmill_2{
			left: 50%;
		}
		#windmill_3{
			display: none;
		}
		#windmill_4{
			display: none;
		}
	}

	@media screen and (min-width: 341px){
  	.windmill{
  	  width: 33%;
  	  height: 50%;
  	  position: fixed;
  	  bottom: 15%;
  	  z-index: 6;
  	}
  	.windmill_relative{
  	  position: relative;
  	  width: 100%;
  	  height: 100%;
  	}
  	.lod{
  	  width: 66%;
  	  height: auto;
  	  position: absolute;
  	  bottom: 0px;
  	  left: 40%;
  	  z-index: 8;
  	}
  	.wind{
  	  width: 100%;
  	  height: auto;
  	  position: absolute;
  	  bottom: 3.5%;
  	  left: 23%;
  	  z-index: 12;
		}

		#windmill_1{
			display: block;
			left: 10%;
			bottom: 18%;
		}
		#windmill_2{
			left: 50%;
		}
		#windmill_3{
			display: none;
		}
		#windmill_4{
			display: none;
		}
	}

	@media screen and (min-width: 601px){
  	.windmill{
  	  width: 18%;
  	  height: 50%;
  	  position: fixed;
  	  bottom: 15%;
  	  z-index: 6;
  	}
  	.windmill_relative{
  	  position: relative;
  	  width: 100%;
  	  height: 100%;
  	}
  	.lod{
  	  width: 66%;
  	  height: auto;
  	  position: absolute;
  	  bottom: 0px;
  	  left: 40%;
  	  z-index: 8;
  	}
  	.wind{
  	  width: 100%;
  	  height: auto;
  	  position: absolute;
  	  bottom: 2%;
  	  left: 23%;
  	  z-index: 12;
		}

		#windmill_1{
			display: block;
			left: 10%;
			bottom: 18%;
		}
		#windmill_2{
			left: 40%;
		}
		#windmill_3{
			display: block;
			left: 66%;
		}
		#windmill_4{
			display: none;
		}
	}
	
	@media screen and (min-width: 801px){
  	.windmill{
  	  width: 18%;
  	  height: 50%;
  	  position: fixed;
  	  bottom: 15%;
  	  z-index: 6;
  	}
  	.windmill_relative{
  	  position: relative;
  	  width: 100%;
  	  height: 100%;
  	}
  	.lod{
  	  width: 66%;
  	  height: auto;
  	  position: absolute;
  	  bottom: 0px;
  	  left: 40%;
  	  z-index: 8;
  	}
  	.wind{
  	  width: 100%;
  	  height: auto;
  	  position: absolute;
  	  bottom: 3%;
  	  left: 23%;
  	  z-index: 12;
		}

		#windmill_1{
			display: block;
			left: 10%;
			bottom: 18%;
		}
		#windmill_2{
			left: 40%;
		}
		#windmill_3{
			display: block;
			left: 66%;
		}
		#windmill_4{
			display: none;
		}
	}

	@media screen and (min-width: 901px){
  	.windmill{
  	  width: 18%;
  	  height: 50%;
  	  position: fixed;
  	  bottom: 15%;
  	  z-index: 6;
  	}
  	.windmill_relative{
  	  position: relative;
  	  width: 100%;
  	  height: 100%;
  	}
  	.lod{
  	  width: 66%;
  	  height: auto;
  	  position: absolute;
  	  bottom: 0px;
  	  left: 40%;
  	  z-index: 8;
  	}
  	.wind{
  	  width: 100%;
  	  height: auto;
  	  position: absolute;
  	  bottom: 3.6%;
  	  left: 23%;
  	  z-index: 12;
		}

		#windmill_1{
			display: block;
			left: 6%;
			bottom: 18%;
		}
		#windmill_2{
			left: 33%;
		}
		#windmill_3{
			display: block;
			left: 54%;
			bottom: 10%;
		}
		#windmill_4{
			display: block;
			left: 74%;
		}
	}

	/*乱数での実装は厳しいのであとで調整する*/
  .rotate{
    -moz-animation: rotate_controller_1 6s linear 10ms infinite forwards;
    -webkit-animation: rotate_controller_1 6s linear 10ms infinite forwards;
    -o-animation: rotate_controller_1 5s linear 20ms infinite forwards;
    -ms-animation: rotate_controller_1 5s linear 20ms infinite forwards;
   }

   @-webkit-keyframes rotate_controller_1 {
    100% {-webkit-transform: rotate(-360deg);}
   }
   @-moz-keyframes rotate_controller_1 {
    100% {-moz-transform: rotate(-360deg);}
   }
   @-ms-keyframes rotate_controller_1 {
    100% {-ms-transform: rotate(-360deg);}
   }
   @-o-keyframes rotate_controller {
    100% {-o-transform: rotate(-360deg);}
	 }
	 
</style>
<%= render("layouts/analytics")%>

api_server/app/views/layouts/_windmill.html.haml
.windmill(id="windmill_#{i+1}" class="#{@blur_on_windmill}")
  .windmill_relative
    = image_tag "wind_#{i+1}.png",class: "wind rotate", id: "wind_#{i+1}"
    = image_tag "mill.png",class: "lod"

api_server/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta(content="width=device-width, initial-scale=1.0 user-scalable=no" name="viewport")

    %title= @title

    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    %link(href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet")

  %body.grey-text
    -if request.fullpath == "/"
      = render "parts/header"
      = render "parts/windmill"
      = render "layouts/page_css"
    - else
      = render "layouts/page_css_dont_move"
      = render "parts/header2"
    = yield
    = render "parts/notice"
    = javascript_include_tag 'application'

api_server/app/views/parts/_header.html.haml
%header.navbar-fixed.under_cover
  %nav.nav-wrapper
    = link_to @title,:root,class: "brand-logo center white-text family_select thin_300"

:css
  .under_cover{
    background: "/designs/blur.png"
  }

api_server/app/views/parts/_header2.html.haml
%header.navbar-fixed.under_cover
  %nav.nav-wrapper
    = link_to "Season's Call",:root,class: "brand-logo center lato thin_300 amber-text"
    %a(href="#" data-activates="mobile-demo" class="button-collapse amber-text" id="menu_posit all_time_show")
      %i.material-icons menu
      
    %a(href="/searches" class="right get_right waves-effect")
      %i.material-icons.amber-text search

    %ul.side-nav#mobile-demo
      = render "parts/header_menu" 
:css
  .under_cover{
    background: "/designs/blur.png"
    /*width: 100%;
    height: 60px;
    filter: blur(66px);
    -webkit-filter: blur(66px);
    -ms-filter: blur(66px);*/
  }

api_server/app/views/parts/_header_menu.html.haml
- ["作品集"].each do |tag|
  %li= link_to tag,:root,class: "thin waves-effect waves-light"
%li= link_to "ブログ", blogs_path, class: "thin waves-effect waves-light"
%li= link_to "このサイトについて", about_index_path, class: "thin waves-effect waves-light"
- if user_signed_in?
  %li= link_to "管理画面へ",@current_user,class: "thin_300 waves-effect waves-light"
  %li= link_to "ログアウト",sign_out_users_path,class: "thin waves-effect waves-light", method: :delete
- else
  %li= link_to "サインイン", sign_in_users_path, class: "thin waves-effect waves-light"

api_server/app/views/parts/_notice.html.haml
- if notice
  :javascript
    Materialize.toast("#{notice}",3330);
- if alert
  :javascript
    Materialize.toast("#{alert}",3330);

api_server/app/views/parts/_windmill.html.haml
#the_world(class="#{@sky} #{@blur}")
  /山の画像を切り替える場合はここから・ω・
  = image_tag "mt.png",id: "mountain",class: "blur"
  - 4.times do |i|
    = render "layouts/windmill",i: i 

api_server/app/views/parts/_windmill_out.html.haml
#the_world(class="#{@sky} #{@blur}")
  = image_tag "mt.png",id: "mountain",class: "blur"
= render "layouts/page_css"

api_server/app/views/searches/edit.html.haml
%h1 Editing search

= render 'form'

= link_to 'Show', @search
\|
= link_to 'Back', searches_path